const loadDB = require("../utils/loadDB").loadDB;
const path = require("path");
const filepath = path.join(__dirname, "../DB/neDB/verify.db");
const db = loadDB(filepath);

/**
 * verifies the code sent by the user against that in the database
 * @param {string} code
 */
class VerifyCode {
    constructor(code, email) {
        this._code = code;
        this._email = email;
    }

    /**
     * stores the verification code generated by the sever
     */
    storeCodeAndEmail() {
        let codeObj = {
            code: this._code,
            email: this._email
        }

        return new Promise((resolve, reject) => {
            db.insert(codeObj, (error, document) => {
                if (error) {
                    reject({error: error})
                }
                else {
                    resolve({error: null, message: document})
                }
            })
        })
    }

    verifyCodeAndEmail() {
        return new Promise((resolve, reject) => {
            db.find(
                {
                    email: this._email,
                    code: this._code
                },
                {mulit: false},
                (error, document) => {
                    if (error) reject({error: error, message: "error verifying code and email"});
                    else {
                        void(document);
                        resolve({error: null, message:"verified"});
                    }
                }
            )
        })
    }

    /**
     * delets verification code and email after it has been verified
     */
    deleteCodeAndEmail() {
        return new Promise((resolve, reject) => {
            db.find(
                {
                    code: this._code,
                    email: this._email
                },
                {multi: false},
                (error, document) => {
                    console.log(document);
                    if(error) reject({error: error});
                    else {
                        db.remove(
                            {_id: document[0]._id},
                            {multi: false},
                            (error, number) => {
                                if(error) reject({error: error});
                                else{
                                    console.log(number, " deleted");
                                    resolve({number: number})
                                }
                            }
                        )
                    }
                }
            )
        })
    }
}

module.exports = VerifyCode;